# Using raise keyword we can raise exception manually.

num = 15

if num <= 15 : raise AssertionError(' Number should be more than 15')


print(' END ')

